name: nf-aggregate CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  pull_request:
  release:
    types:
      - published
  merge_group:
    types:
      - checks_requested
    branches:
      - master

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tags.outputs.tags }}
    steps:
      - uses: actions/checkout@v3
      - name: Combine all tags.yml files
        id: get_username
        run: find . -name "tags.yml" -not -path "./.github/*" -exec cat {} + > .github/tags.yml
      - name: debug
        run: cat .github/tags.yml
      - name: Get tags using yq
        id: get_tags
        uses: mikefarah/yq@master
        run: |
          tags="$(yq -e '. | keys | tojson' .github/tags.yml)"
          echo "tags=$tags" >> "$GITHUB_OUTPUT"

  nf-test:
    name: nf-test ${{ matrix.tags }} ${{ matrix.profile }}
    needs: [changes]
    if: needs.changes.outputs.tags != '[]'
    runs-on: ubuntu-latest
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "23.10.0"
          - "latest-everything"
        tags: ${{ fromJson(needs.changes.outputs.tags) }}
        profile:
          - "docker"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Cache nf-test installation
        id: cache-software
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/bin/nf-test
            /home/runner/.nf-test/nf-test.jar
          key: ${{ runner.os }}-${{ env.NFTEST_VER }}-nftest

      - name: Install nf-test
        if: steps.cache-software.outputs.cache-hit != 'true'
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run nf-test
        run: |
          nf-test test --tag ${{ matrix.tags }} --profile "test,${{ matrix.profile }}" --junitxml=test.xml

      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always ${{ github.workspace }}/.nf-test/tests/*/meta/nextflow.log

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: test.xml
